allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}
android {
    namespace 'com.example.flutter_secure_storage' // Replace with the actual package name
    compileSdk 33

    defaultConfig {
        minSdk 21
        targetSdk 33
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
